/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondpro;

import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;

/**
 *
 * @author h
 */
public class JuegoPreguntas extends javax.swing.JFrame {

    /**
     * Creates new form JuegoPreguntas
     */
    public JuegoPreguntas() {
        initComponents();
        ImageIcon tablero = new ImageIcon(getClass().getResource("/imagenes/TableroPreguntas.jpg"));
        ImageIcon montar = new ImageIcon(tablero.getImage().getScaledInstance(tabJuego.getWidth(),tabJuego.getHeight(),Image.SCALE_DEFAULT));
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabJuego = new javax.swing.JPanel();
        ini = new javax.swing.JButton();
        exi = new javax.swing.JButton();
        personaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ini.setText("Empezar");
        ini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniActionPerformed(evt);
            }
        });

        exi.setText("Salir");
        exi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tabJuegoLayout = new javax.swing.GroupLayout(tabJuego);
        tabJuego.setLayout(tabJuegoLayout);
        tabJuegoLayout.setHorizontalGroup(
            tabJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabJuegoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ini)
                .addGap(69, 69, 69)
                .addComponent(exi)
                .addContainerGap(528, Short.MAX_VALUE))
        );
        tabJuegoLayout.setVerticalGroup(
            tabJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(tabJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ini)
                    .addComponent(exi))
                .addContainerGap())
        );

        personaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                personajeKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabJuego, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(personaje, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addComponent(tabJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniActionPerformed
        //Aquí se debe de iniciar el resto de metodos del juego
        ImageIcon user = new ImageIcon(getClass().getResource("/imagenes/User.jpg"));
        ImageIcon icono = new ImageIcon(user.getImage().getScaledInstance(personaje.getWidth(), personaje.getHeight(), Image.SCALE_DEFAULT));
        personaje.setIcon(icono);
        
    }//GEN-LAST:event_iniActionPerformed

    private void exiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exiActionPerformed
        MenuPreguntas v = new MenuPreguntas();
        v.setVisible(true);
        dispose();
    }//GEN-LAST:event_exiActionPerformed

    private void personajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_personajeKeyPressed
        
        
    }//GEN-LAST:event_personajeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegoPreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoPreguntas().setVisible(true);
            }
        });
    }
    private Image img;

    
    public void ImagePanel(Image img){
        this.img = img;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exi;
    private javax.swing.JButton ini;
    private javax.swing.JLabel personaje;
    private javax.swing.JPanel tabJuego;
    // End of variables declaration//GEN-END:variables
}
