/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondpro;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.border.Border;

/**
 *
 * @author Sebastian
 */
public class Preguntas extends javax.swing.JFrame {

    /**
     * Creates new form Preguntas
     */
        
    JLabel eti = new JLabel();
    JLabel [][] etiq = new JLabel[5][8];
    String [][] logic = new String[5][8];
    public Preguntas() {
        initComponents();
        show1();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout tabLayout = new javax.swing.GroupLayout(tab);
        tab.setLayout(tabLayout);
        tabLayout.setHorizontalGroup(
            tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        tabLayout.setVerticalGroup(
            tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        PregLogica x = new PregLogica();
        int code;
        if(evt.getKeyCode()== 39){
            if(x.derecha(logic)){
                code = 39;
                cambio(code);
                tab.removeAll();
                tab.setVisible(false);
                tab.setVisible(true);
                mostrar(etiq,logic);
                
                System.out.println("si");
                
            }
            else{
                System.out.println("no");
            }
        }else if(evt.getKeyCode() == 37){
            if(x.izquierda(logic)){
                code = 37;
                cambio(code);
                tab.removeAll();
                tab.setVisible(false);
                tab.setVisible(true);
                mostrar(etiq,logic);
                System.out.println("si");
            }
            else{
                System.out.println("no");
            }
        }
        else if(evt.getKeyCode()== 38){
            if(x.arriba(logic)){
                code = 38;
                cambio(code);
                tab.removeAll();
                tab.setVisible(false);
                tab.setVisible(true);
                mostrar(etiq,logic);
                System.out.println("si");
                        
            }
            else{
                System.out.println("no");
            }
        }
        else if(evt.getKeyCode()== 40){
            if(x.abajo(logic)){
                code = 40;
                cambio(code);
                tab.removeAll();
                tab.setVisible(false);
                tab.setVisible(true);
                mostrar(etiq,logic);
                System.out.println("si");
            }
            else{
                System.out.println("no");
            }
        }
        else{
            JOptionPane.showMessageDialog(rootPane,"Tecla invalida");
        }
    }//GEN-LAST:event_formKeyPressed
    //Allows to show the matrix
    public void show1(){
        int x =(int) (Math.random() * 5) + 0;
        int y =(int) (Math.random() * 8) + 0;
        logic[x][y]= "$";
        logic[4][7] = "1";
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                if(logic[i][j] == null){
                    logic[i][j] = "_";
            }}
        }
        int conta = 0;
        while(conta < 10){
            int alex =(int) (Math.random() * 5) + 0;
            int aley =(int) (Math.random() * 8) + 0;
            if(logic[alex][aley].equals("_")){
                logic[alex][aley]= "*";
                conta++;
            }
             
            
        }
        logic[0][0] = "u";
            
        
        mostrar(etiq,logic);
    
    
    }
     
     //Allows to show the matrix with the graphic interface
    public void mostrar(JLabel[][] etiquetas,String[][]logica){
        int  x = 75;
        int  y = 75;
        Border border = BorderFactory.createLineBorder(Color.black, 1);
        
        
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {

                if(logica[i][j].equals("_")){
                   ImageIcon paso = new ImageIcon(this.getClass().getResource("/imagenes/paso.jpg"));
                   etiquetas[i][j] = new JLabel();
                   etiquetas[i][j].setBounds(x, y, 75, 75);
                   etiquetas[i][j].setIcon(paso);
                   etiquetas[i][j].setBorder(border);
                   tab.add(etiquetas[i][j]);
                }
                else if(logica[i][j].equals("*")){
                   ImageIcon obsta = new ImageIcon(this.getClass().getResource("/imagenes/muro.jpg"));
                   etiquetas[i][j] = new JLabel();
                   etiquetas[i][j].setBounds(x, y, 75, 75);
                   etiquetas[i][j].setIcon(obsta);
                   etiquetas[i][j].setBorder(border);
                   
                   tab.add(etiquetas[i][j]);
                }else if(logica[i][j].equals("$")){
                    ImageIcon obsta = new ImageIcon(this.getClass().getResource("/imagenes/como.jpg"));
                    etiquetas[i][j] = new JLabel();
                   etiquetas[i][j].setBounds(x, y, 75, 75);
                   etiquetas[i][j].setIcon(obsta);
                   etiquetas[i][j].setBorder(border);
                   
                   tab.add(etiquetas[i][j]);                    
                }
                else if(logica[i][j].equals("u")){
                    ImageIcon user = new ImageIcon(this.getClass().getResource("/imagenes/User.jpg"));
                    etiquetas[i][j] = new JLabel();
                    etiquetas[i][j].setBounds(x, y, 75, 75);
                    etiquetas[i][j].setIcon(user);
                    etiquetas[i][j].setBorder(border);
                    tab.add(etiquetas[i][j]);
                    
                }
                else{
                    ImageIcon meta = new ImageIcon(this.getClass().getResource("/imagenes/meta.jpg"));
                    etiquetas[4][7] = new JLabel();
                    etiquetas[4][7].setBounds(x, y, 75, 75);
                    etiquetas[4][7].setIcon(meta);
                    etiquetas[4][7].setBorder(border);
                
                }
                x= x+75;
            }
            x = 75;
            y = y+75;
        }
        
        tab.add(etiquetas[4][7]);
//        tab.setVisible(false);
//        tab.setVisible(true);
    }
    
    public void cambio( int code){
        int round = 0;
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 8; j++) {
                
                if (logic[i][j].equals("u")) {
                    if(code == 39){
                        //Right
                        logic[i][j+1] = "u";
                        logic[i][j] = "_";
                        round = 1;
                        break;
                    }
                    else if(code == 37){
                        //Left
                        logic[i][j-1] = "u";
                        logic[i][j] = "_";
                        round = 1;
                        break;
                    }
                    else if(code == 38){
                        //Up
                        logic[i-1][j] = "u";
                        logic[i][j] = "_";
                        round = 1;
                        break;
                    }
                    else{
                        //Down
                        System.out.println(i);
                        logic[i+1][j] = "u";
                        logic[i][j] = "_";
                        round = 1;
                        break;
                    }
                } 
                
            }
            if(round == 1){
                break;
            }
        }
    
    
    
    }
    
    
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Preguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Preguntas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel tab;
    // End of variables declaration//GEN-END:variables
}
